name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build for Multiple Platforms
        run: |
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o dist/nlsh-linux-amd64
          GOOS=linux GOARCH=arm64 go build -o dist/nlsh-linux-arm64

          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o dist/nlsh-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o dist/nlsh-darwin-arm64

          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o dist/nlsh-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -o dist/nlsh-windows-arm64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/nlsh-linux-amd64
            dist/nlsh-linux-arm64
            dist/nlsh-darwin-amd64
            dist/nlsh-darwin-arm64
            dist/nlsh-windows-amd64.exe
            dist/nlsh-windows-arm64.exe
          generate_release_notes: true
